Outlook update
annich-MS/DefinitelyTyped pull request #1
Opened 2017-02-21 18:04 UTC by annich-MS

View each commit separately for easiest understanding

2017-02-23 22:18 UTC, kfmpchan commented on office-js/index.d.ts
>          /**
NotificationMessage has string key, not recipients
https://dev.outlook.com/reference/add-ins/NotificationMessages.html

2017-02-23 22:32 UTC, kfmpchan requested changes

2017-02-23 22:32 UTC, kfmpchan commented on office-js/index.d.ts
> +    export enum SourceProperty {
Not sure why we documented this, but I don't think this needs to be publicly exposed.  Which API uses this?

2017-02-23 22:32 UTC, kfmpchan commented on office-js/index.d.ts
>          /**
nvm, saw this fixed in latter commits

2017-02-23 22:32 UTC, kfmpchan commented on office-js/index.d.ts
>          /**
wait, I switched view and addAsync is showing up under PhoneNumber?  diff issue?

2017-02-24 06:28 UTC, Zlatkovsky commented on office-js/index.d.ts
> +             * A meeting request, response, or cancellation
Comment seems wrong (maybe?).  Message does seem to correspond with " A meeting request, response, or cancellation"

2017-02-24 06:28 UTC, Zlatkovsky commented on office-js/index.d.ts
> +            Other,
Nit: I would put "other" at the bottom.

2017-02-24 06:28 UTC, Zlatkovsky commented on office-js/index.d.ts
> +         * Gets an array of entities found in an message
"Array" doesn't seem to really be correct.  The entities contains a bunch of arrays within it, but it itself is not an array.

2017-02-24 06:28 UTC, Zlatkovsky commented on office-js/index.d.ts
>           * @param options Any optional parameters or state data passed to the method
Here and elsewhere:  does options have any structure, more than just "any"?

2017-02-24 06:28 UTC, Zlatkovsky commented on office-js/index.d.ts
> +        addAsync(key: string, JSONmessage: NotificationMessage, options?: any, callback?: (result: AsyncResult) => void): void;
One thing I would love to do is convert AsyncResult to a generics type, which would make it infinitely more useful (typing the `value` to something useful).  Looks like you're adding a bunch of them.  Could I take a few hours tomorrow to make a pull request for converting AsyncResults, and then have you adjust your code, before you add a bunch of these new ones?

2017-02-24 17:40 UTC, annich-MS commented on office-js/index.d.ts
> +        addAsync(key: string, JSONmessage: NotificationMessage, options?: any, callback?: (result: AsyncResult) => void): void;
That sounds good. add me to the PR so I know I can do a merge

2017-02-24 17:50 UTC, annich-MS commented on office-js/index.d.ts
>           * @param options Any optional parameters or state data passed to the method
These options do have defined structures, however many are unique, and I was hesitant to add 20+ new interfaces that were only used once. I agree that they're worthwhile, so I'll add them in the next revision

2017-02-24 17:54 UTC, annich-MS commented on office-js/index.d.ts
>          /**
On the sidebar there's a little symbol (looks like an arrow pointing up and down) that represents a cut. clicking on it shows the space in the middle, and shows that this line is under Recipients. I think this is a bug on github

2017-02-24 17:57 UTC, annich-MS commented on office-js/index.d.ts
> +             * A meeting request, response, or cancellation
This one slipped by me, will be in next revison

2017-02-24 18:00 UTC, annich-MS commented on office-js/index.d.ts
> +    export enum SourceProperty {
The order I did this work was had me fixing the enums before using them, so I didn't notice that this wasn't being used. Looks like this isn't being used currently, but it is documented: https://dev.outlook.com/reference/add-ins/Office.html#.SourceProperty

2017-02-24 18:06 UTC, annich-MS commented on office-js/index.d.ts
> +         * Gets an array of entities found in an message
Right, will update

2017-02-25 05:14 UTC, Zlatkovsky commented on office-js/index.d.ts
>           * @param options Any optional parameters or state data passed to the method
You can inline the options as an object.  I.e., 

    function foo(options: {items: number; pattern: string; somethingElse: any} )

2017-02-25 05:14 UTC, Zlatkovsky commented on office-js/index.d.ts
> +        addAsync(key: string, JSONmessage: NotificationMessage, options?: any, callback?: (result: AsyncResult) => void): void;
I did not get a a chance to update AsyncResult to use Generics.  And in fact, it may take a bit more time than I though.
So go ahead, don't stall on me.  Feel free to submit a pull request as is.  We will let you know once we need your help with async result.

2017-07-05 17:15 UTC, merged